_commit: 0bea33c
_src_path: git@github.com:adrisala/copier-boilerplate.git
author_name: adrisala
django_version: '5.2'
maintainer_name: tester
project_name: Service Example
project_short_description: A Django REST Framework service
project_slug: service_example
python_version: '3.12'
version: 0.1.0
